name: C/C++ with Make

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # ---------------- Linux ----------------
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake xorg-dev libglu1-mesa-dev
        git clone https://github.com/raysan5/raylib.git --depth=1
        cd raylib/src
        make PLATFORM=PLATFORM_DESKTOP
        sudo make install

    # ---------------- macOS ----------------
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install raylib make

    # ---------------- Build ----------------
    - name: Build with Make
      run: make all

    # ---------------- Upload Artifact ----------------
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: stegachat-${{ matrix.os }}
        path: ./bin/stegachat
